name: GitHub Metrics
on:
  schedule: [{cron: "0 * * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: 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
          user: Microman
          filename: metrics.repository.svg
          template: repository
          base: header, activity, community, repositories, metadata
          plugin_traffic: yes
