name: Metrics
on:
  # Schedule updates
  schedule: [{cron: "0 */24 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  # push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{secrets.METRICS_TOKEN}} 
          # Options
          organization: ByteCats
          template: repository
          Repository: microman
          base: header, activity, community, repositories, metadata
          plugin_traffic: yes
